# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-02 03:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='AgentDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('middle_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('father_name', models.CharField(max_length=50)),
                ('mother_name', models.CharField(max_length=50)),
                ('pancard', models.CharField(max_length=50, null=True)),
                ('address', models.TextField()),
                ('date_of_birth', models.DateField()),
                ('contact_no', models.CharField(max_length=15)),
                ('alternate_contact_no', models.CharField(max_length=15, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='advisor-images')),
                ('date_of_joining', models.DateField()),
                ('percentage_alloted', models.FloatField()),
                ('introducer_percentage', models.FloatField(null=True)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grom.AgentAccount')),
                ('introducor_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='grom.AgentDetail')),
            ],
        ),
        migrations.CreateModel(
            name='AgentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('middle_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('pancard', models.CharField(max_length=50, null=True)),
                ('address', models.TextField()),
                ('contact_no', models.CharField(max_length=15)),
                ('alternate_contact_no', models.CharField(max_length=15, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('date_of_joining', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='LandDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('belonging_to', models.CharField(max_length=50)),
                ('ph_no', models.CharField(max_length=20)),
                ('survey_no', models.CharField(max_length=20)),
                ('village', models.CharField(max_length=50)),
                ('panchayat', models.CharField(max_length=50)),
                ('tehsil', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('taluka', models.CharField(max_length=50)),
                ('irrigation', models.CharField(max_length=50)),
                ('broker_name', models.CharField(max_length=100)),
                ('purchase_date', models.DateField()),
                ('total_area', models.FloatField()),
                ('rate', models.FloatField()),
                ('total_cost', models.FloatField()),
                ('registeration_date', models.DateField()),
                ('amount', models.FloatField()),
                ('advance_amount', models.FloatField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LayoutDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout_name', models.CharField(max_length=50)),
                ('remark', models.TextField()),
                ('date', models.DateField()),
                ('area_under_layout', models.FloatField()),
                ('area_under_plot', models.FloatField()),
                ('area_under_possession', models.FloatField()),
                ('area_under_open_space', models.FloatField()),
                ('area_under_public_utility', models.FloatField()),
                ('area_under_road', models.FloatField()),
                ('land_detail_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grom.LandDetail')),
            ],
        ),
        migrations.CreateModel(
            name='NominiDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('relation', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('contact_no', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('belong_to', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PlotDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot_number', models.CharField(max_length=10)),
                ('remark', models.TextField()),
                ('date', models.DateField()),
                ('total_area', models.FloatField()),
                ('tan_area', models.FloatField()),
                ('net_area', models.FloatField()),
                ('status', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('land_detail_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grom.LandDetail')),
                ('layout_detail_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grom.LayoutDetail')),
            ],
        ),
        migrations.CreateModel(
            name='StaffUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loginid', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('fullname', models.CharField(max_length=100)),
                ('contact_no', models.CharField(max_length=15)),
                ('alternate_contact_no', models.CharField(max_length=15, null=True)),
                ('address', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='plotdetail',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grom.ProjectDetail'),
        ),
        migrations.AddField(
            model_name='agentdetail',
            name='nomini_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grom.NominiDetail'),
        ),
        migrations.AddField(
            model_name='agentdetail',
            name='type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grom.AgentType'),
        ),
    ]
