# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-26 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('belonging_to', models.CharField(max_length=50)),
                ('ph_no', models.CharField(max_length=20)),
                ('survey_no', models.CharField(max_length=20)),
                ('village', models.CharField(max_length=50)),
                ('panchayat', models.CharField(max_length=50)),
                ('tehsil', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('taluka', models.CharField(max_length=50)),
                ('irrigation', models.CharField(max_length=50)),
                ('broker_name', models.CharField(max_length=100)),
                ('purchase_date', models.DateField()),
                ('total_area', models.FloatField()),
                ('rate', models.FloatField()),
                ('total_cost', models.FloatField()),
                ('registeration_date', models.DateField()),
                ('amount', models.FloatField()),
                ('advance_amount', models.FloatField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='staffuser',
            name='alternate_contact_no',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='staffuser',
            name='loginid',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
