# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-14 14:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grom', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nominidetail',
            name='belong_to',
        ),
        migrations.AddField(
            model_name='customerdetail',
            name='nomini',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='grom.NominiDetail'),
        ),
        migrations.AddField(
            model_name='customerdetail',
            name='plot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='grom.PlotDetail'),
        ),
    ]
