# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-09 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grom', '0004_auto_20161109_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentdetail',
            name='introducer_percentage',
            field=models.FloatField(null=True),
        ),
    ]
