# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-22 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grom', '0006_auto_20161122_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentdetail',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='advisor-images'),
        ),
    ]
